name: Get weekly book list
env:
  TZ: Asia/Taipei
on:
  schedule:
    - cron: '0 1 * * 4'
jobs:
  create_weekly_book_list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: get_book_list
      run: |
        python get_book_list.py
    - uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: Commit latest on sales book list
