name: Book parser and notifier
env:
  TZ: Asia/Taipei
on:   
  schedule:
    - cron: '10 1 * * *'
jobs:
  book_parser_and_notification_sender:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Parser the book info and send out the notification
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
      run: |
        python book_parser.py
