name: Telegram message
on: 
    push:
    schedule:
        - cron: '0 1 * * *'
jobs:
  build:
    name: Build Telegram Notifier
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send telegram notification
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: Hello World
